collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4121864
  brandStrength: 0.7849463
  lightness: 0.9507719
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  rhythmicContrast: 0.792726
typography_spectrum: 0.4336918
layout_spectrum: 0.6559139
name: 'Design. Print. Mail. Lots of love. '
