collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7580645
  brandStrength: 0.4964158
  lightness: 1
  brandColors:
    - '#F7F5F4'
    - '#3B3836'
    - '#A39476'
    - '#020202'
    - '#007AFF'
  rhythmicContrast: 1
typography_spectrum: 0.4336918
layout_spectrum: 0
name: 'Design. Print. Mail. Lots of love. '
