layout_spectrum: 0.5017921
color:
  saturation: 0.3269558
  lightness: 0.9507719
  brandStrength: 0.9156693
  rhythmicContrast: 0.792726
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.2648399
name: 'Design. Print. Mail. Lots of love. '
