collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4121864
  brandStrength: 0.6559139
  lightness: 0.9507719
  brandColors:
    - '#000000'
    - '#F2D8BD'
    - '#C5BD02'
    - '#F202BD'
    - '#6E3030'
  rhythmicContrast: 0.792726
typography_spectrum: 0.4336918
layout_spectrum: 0.6559139
name: 'Design. Print. Mail. Lots of love. '
